import { environment } from "./environment";

// TODO: MOVE ALL CONSTANTS HERE
export const AppConstants = {
  API_ENDPOINTS: {
    TEST_URL: "test/test",
    LOG_URL: "log",
    ACCOUNT_URL: "api/token",
    DUMMY_TEACHER_URL: "api/v1/DummyTeacher",
    DUMMY_STUDENT_URL: "api/token",
    CLIENT_USER: "/api/v1/ClientUser",
    RENO_ADS: "api/v1/RenoAds",
    CompanyAdditionalInfo: "api/v1/CompanyAdditionalInfo",
    EXTERNAL_USER: "/api/v1/ExternalUser",
    FEEDBACK: "api/v1/Feedback",
    ApplicationFile: "api/v1/ApplicationFile",
    ClientCompanyAdditionalInfo: "api/v1/ClientCompanyAdditionalInfo",
  },
  DATABASE_KEYS: {
    ACCESS_TOKEN: "ACCESS_TOKEN",
    LOGIN_USER: "LOGIN_USER",
    API_RESP_CACHE: "API_RESP_CACHE",
    PLATFORM: "PLATFORM",
    REMEMBER_PWD: "REMEMBER_PWD",
    COMPANY_CODE: "COMPANY_CODE",
    AUTOMATION_TOKEN: "AUTOMATION_TOKEN",
    AUTOMATION_USER: "AUTOMATION_USER",
    APP_LOGS: "APP_LOGS",
    EXCEPTION_LOGS: "EXCEPTION_LOGS",
    USER: "USER",
    FEEDBACK_INFO: "FEEDBACK_INFO",
  },
  DATABASE_DEFAULT_VALUES: {},
  ERROR_PROMPTS: {
    App_StartError: "Error occured. Please restart the application.",
    Load_Data_Error: "Error in loading data. Please try again.",
    Invalid_Input_Data: "Invalid data.Please try again.",
    Unknown_Error: "Error occured. Please try again.",
    Network_Error: "Please check network and try again.",
    Save_Data_Error: "Error in saving. Please try again.",
    Delete_Data_Error: "Error in delete. Please try again.",
    Permission_Error: "Permission denied.",
    Unauthorized_User: "User not authorized. Please relogin.",
  },
  HEADER_NAMES: {
    ApiType: "targetapitype",
    DevApk: "isdeveloperapk",
    AppVersion: "appversion",
    // CORS_ALLOW_ORIGIN: "Access-Control-Allow-Origin",
    // CORS_ALLOW_METHODS: "Access-Control-Allow-Methods",
    // CORS_ALLOW_CREDENTIALS: "Access-Control-Allow-Credentials",
  },
  HEADER_VALUES: {
    ApiType: "abcd",
    DevApk: (!environment.production).toString(),
    AppVersion: environment.applicationVersion,
    // CORS_ALLOW_ORIGIN: "http://localhost:4200",
    // CORS_ALLOW_METHODS: "GET, POST, OPTIONS, DELETE, PUT",
    // CORS_ALLOW_CREDENTIALS: "true",
  },
  WEB_ROUTES: {
    ENDUSER: {
      SAMPLE: "sample",
      DummyTeacher: "dummyTeacher",
      UNAUTHORIZED: "",
      LOGIN: "login",
      HOME: "home",
    },
    SUPERADMIN: {
      LOGIN: "superadmin/login",
      DASHBOARD: "superadmin/dashboard",
    },
    NOTFOUND: "**",
  },
  TOKEN_KEY_NAMES: {
    Role: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
    Expiry: "exp",
    CompanyCode: "clCd",
    Audience: "aud",
    CompanyId: "clId",
    RecordId: "dbRId",
    EmailAddress:
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
    UserName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
    GivenName:
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
    Issuer: "iss",
    TokenStart: "nbf",
  },
};
